//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseUTS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRelationships
    {
        public int ID { get; set; }
        public string CourseID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string ChoiceBlockID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int SubjectTypeID { get; set; }
        public int Stage { get; set; }
        public int Year { get; set; }
    
        public virtual ChoiceBlocks ChoiceBlocks { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual SubjectGroupingsCredit SubjectGroupingsCredit { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual SubjectTypes SubjectTypes { get; set; }
    }
}
