//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseUTS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMajorRelationships
    {
        public int ID { get; set; }
        public string CourseID { get; set; }
        public string MajorID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Majors Majors { get; set; }
    }
}
