
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCourseUTS.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Majors
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Majors()
    {

        this.CourseRelationships = new HashSet<CourseRelationships>();

        this.SubjectGroupingRelationships = new HashSet<SubjectGroupingRelationships>();

    }


    public string ID { get; set; }

    public decimal Version { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public int CreditPoints { get; set; }

    public bool Active { get; set; }

    public string MajorDescription { get; set; }

    public string VersionDescription { get; set; }

    public int Stages { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CourseRelationships> CourseRelationships { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SubjectGroupingRelationships> SubjectGroupingRelationships { get; set; }

}

}
