//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseUTS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisiteRelationship
    {
        public int ID { get; set; }
        public int SubjectID { get; set; }
        public int RequisiteID { get; set; }
        public int RequisiteTypeID { get; set; }
    
        public virtual RequisiteTypes RequisiteTypes { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Subjects Subjects1 { get; set; }
    }
}
