//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseUTS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectGroupingsCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectGroupingsCredit()
        {
            this.ChoiceBlockRelationships = new HashSet<ChoiceBlockRelationships>();
            this.CourseRelationships = new HashSet<CourseRelationships>();
            this.MajorRelationships = new HashSet<MajorRelationships>();
            this.StreamRelationships = new HashSet<StreamRelationships>();
            this.SubjectGroupings = new HashSet<SubjectGroupings>();
            this.SubMajorRelationships = new HashSet<SubMajorRelationships>();
        }
    
        public int ID { get; set; }
        public int CreditPoints { get; set; }
        public int SubjectPresent { get; set; }
        public int MajorPresent { get; set; }
        public int ChoiceBlockPresent { get; set; }
        public int StreamPresent { get; set; }
        public int SubMajorPresent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiceBlockRelationships> ChoiceBlockRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRelationships> CourseRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MajorRelationships> MajorRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StreamRelationships> StreamRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectGroupings> SubjectGroupings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubMajorRelationships> SubMajorRelationships { get; set; }
    }
}
