//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseUTS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectGroupings
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string MajorID { get; set; }
        public string ChoiceBlockID { get; set; }
        public string StreamID { get; set; }
        public string SubMajorID { get; set; }
    
        public virtual ChoiceBlocks ChoiceBlocks { get; set; }
        public virtual Majors Majors { get; set; }
        public virtual Streams Streams { get; set; }
        public virtual SubjectGroupingsCredit SubjectGroupingsCredit { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual SubMajors SubMajors { get; set; }
    }
}
